# Generated by Django 5.2.17 on 2026-10-01 05:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='debugsession',
            name='patch',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='debugsession',
            name='test_output',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='debugsession',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='debugsession',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('running', 'Running'), ('awaiting_approval', 'Awaiting Approval'), ('fixed', 'Fixed'), ('failed', 'Failed')], default='pending', max_length=30),
        ),
    ]
