# Generated by Django 5.2.17 on 2026-10-01 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_debugsession_patch_debugsession_test_output_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='debugsession',
            name='approval_required',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='debugsession',
            name='approved_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='debugsession',
            name='patch_risk_level',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AddField(
            model_name='debugsession',
            name='security_findings',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='debugsession',
            name='security_review',
            field=models.TextField(blank=True),
        ),
    ]
