# Generated by Django 5.2.17 on 2026-10-02 04:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0003_debugsession_approval_required_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='debugsession',
            name='generated_test_code',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='debugsession',
            name='generated_test_filename',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='debugsession',
            name='generated_test_output',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='debugsession',
            name='generated_test_passed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='debugsession',
            name='generated_test_reason',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='debugsession',
            name='generated_test_saved',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='debugsession',
            name='generated_test_saved_path',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='debugsession',
            name='generated_test_status',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AddField(
            model_name='debugsession',
            name='test_generation_error',
            field=models.TextField(blank=True),
        ),
    ]
