# Generated by Django 5.2.17 on 2026-10-02 05:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0004_debugsession_generated_test_code_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='debugsession',
            name='generated_test_saved',
        ),
        migrations.RemoveField(
            model_name='debugsession',
            name='generated_test_saved_path',
        ),
        migrations.AddField(
            model_name='debugsession',
            name='generated_test_context',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='debugsession',
            name='test_generation_status',
            field=models.CharField(blank=True, default='', max_length=30),
        ),
        migrations.AlterField(
            model_name='debugsession',
            name='generated_test_code',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='debugsession',
            name='generated_test_filename',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='debugsession',
            name='generated_test_output',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='debugsession',
            name='generated_test_reason',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='debugsession',
            name='generated_test_status',
            field=models.CharField(blank=True, default='', max_length=30),
        ),
        migrations.AlterField(
            model_name='debugsession',
            name='test_generation_error',
            field=models.TextField(blank=True, default=''),
        ),
    ]
