"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 5.2.17.
"""

from pathlib import Path


# ============================================================
# BASE DIRECTORY
# ============================================================

BASE_DIR = Path(__file__).resolve().parent.parent


# ============================================================
# SECURITY
# ============================================================

SECRET_KEY = 'django-insecure-3exvlrtul0((#ajojw(+3valw3rs$l7&xf&3tc90=ajxth71_g'

DEBUG = True

ALLOWED_HOSTS = []


# ============================================================
# APPLICATIONS
# ============================================================

INSTALLED_APPS = [

    # Django built-in applications
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",

    # Our applications
    "dashboard",
    "projects",
]


# ============================================================
# MIDDLEWARE
# ============================================================

MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",

    "django.contrib.sessions.middleware.SessionMiddleware",

    "django.middleware.common.CommonMiddleware",

    "django.middleware.csrf.CsrfViewMiddleware",

    "django.contrib.auth.middleware.AuthenticationMiddleware",

    "django.contrib.messages.middleware.MessageMiddleware",

    "django.middleware.clickjacking.XFrameOptionsMiddleware",
]


# ============================================================
# URL CONFIGURATION
# ============================================================

ROOT_URLCONF = "config.urls"


# ============================================================
# TEMPLATES
# ============================================================

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",

        # Our main templates directory
        "DIRS": [
            BASE_DIR / "templates",
        ],

        # Also search inside app/templates/
        "APP_DIRS": True,

        "OPTIONS": {
            "context_processors": [

                "django.template.context_processors.request",

                "django.contrib.auth.context_processors.auth",

                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]


# ============================================================
# WSGI
# ============================================================

WSGI_APPLICATION = "config.wsgi.application"


# ============================================================
# DATABASE
# ============================================================

DATABASES = {
    "default": {
        "ENGINE": "django.db.backends.sqlite3",

        "NAME": BASE_DIR / "db.sqlite3",
    }
}


# ============================================================
# PASSWORD VALIDATION
# ============================================================

AUTH_PASSWORD_VALIDATORS = [

    {
        "NAME":
            "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },

    {
        "NAME":
            "django.contrib.auth.password_validation.MinimumLengthValidator",
    },

    {
        "NAME":
            "django.contrib.auth.password_validation.CommonPasswordValidator",
    },

    {
        "NAME":
            "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]


# ============================================================
# INTERNATIONALIZATION
# ============================================================

LANGUAGE_CODE = "en-us"

TIME_ZONE = "Asia/Kolkata"

USE_I18N = True

USE_TZ = True


# ============================================================
# STATIC FILES
# ============================================================

STATIC_URL = "static/"

STATICFILES_DIRS = [
    BASE_DIR / "static",
]


# ============================================================
# MEDIA / USER UPLOADED FILES
# ============================================================

MEDIA_URL = "/media/"

MEDIA_ROOT = BASE_DIR / "media"


# ============================================================
# PROJECT WORKSPACE
# ============================================================

# Temporary workspace where uploaded projects will be extracted
# and analyzed by the AI agent.

WORKSPACE_ROOT = BASE_DIR / "workspace"

WORKSPACE_ROOT.mkdir(
    parents=True,
    exist_ok=True
)


# ============================================================
# AGENT CONFIGURATION
# ============================================================

# Maximum number of times the agent can attempt to repair
# a project during one debugging session.

AGENT_MAX_ITERATIONS = 5


# Maximum amount of time allowed for a test execution.
# This will be used later by our sandbox/test runner.

AGENT_TEST_TIMEOUT = 60


# ============================================================
# OLLAMA CONFIGURATION
# ============================================================

# Local Ollama server

OLLAMA_BASE_URL = "http://localhost:11434"

# Change this if you install another model through Ollama.

OLLAMA_MODEL = "qwen2.5-coder:7b"


# ============================================================
# GIT CONFIGURATION
# ============================================================

# Enable Git checkpoints before AI modifies project files.

ENABLE_GIT_CHECKPOINTS = True


# ============================================================
# AGENT SAFETY
# ============================================================

# The agent should initially work only with Python projects.

ALLOWED_PROJECT_EXTENSIONS = [
    ".py",
    ".txt",
    ".json",
    ".yaml",
    ".yml",
    ".toml",
    ".ini",
    ".md",
]


# Files/directories that the AI agent should never modify.

PROTECTED_PATHS = [
    ".git",
    ".env",
    "venv",
    ".venv",
    "__pycache__",
]


# ============================================================
# DEFAULT PRIMARY KEY
# ============================================================

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"


# ============================================================
# PHASE 4 SECURITY
# ============================================================

AGENT_MAX_PATCH_LINES = 200

AGENT_REQUIRE_HUMAN_APPROVAL = True

AGENT_BLOCK_CRITICAL_PATCHES = True

AGENT_PROTECTED_PATHS = [
    ".git",
    ".env",
    ".env.local",
    ".env.production",
    ".env.development",
    "venv",
    ".venv",
    "env",
    "__pycache__",
    ".pytest_cache",
    ".mypy_cache",
    ".ruff_cache",
    "node_modules",
]

AGENT_PROTECTED_FILES = [
    "settings.py",
    "manage.py",
    "requirements.txt",
]

# ============================================================
# PHASE 7 - PROJECT MEMORY
# ============================================================

MEMORY_ENABLED = True

MEMORY_ROOT = BASE_DIR / "memory_data"

CHROMA_PERSIST_DIRECTORY = MEMORY_ROOT / "chroma"

CHROMA_COLLECTION_NAME = "developer_memory"

OLLAMA_EMBEDDING_MODEL = "nomic-embed-text"

MEMORY_TOP_K = 5

MEMORY_MAX_CONTEXT_CHARS = 12000

MEMORY_ROOT.mkdir(
    parents=True,
    exist_ok=True,
)

CHROMA_PERSIST_DIRECTORY.mkdir(
    parents=True,
    exist_ok=True,
)

# ============================================================
# PHASE 8 - DOCKER SANDBOX
# ============================================================

EXECUTION_MODE = "docker"

DOCKER_SANDBOX_IMAGE = "self-healing-agent-sandbox:py311"

DOCKER_SANDBOX_TIMEOUT = 60

DOCKER_SANDBOX_MEMORY = "512m"

DOCKER_SANDBOX_CPUS = 1.0

DOCKER_SANDBOX_PIDS_LIMIT = 128

DOCKER_SANDBOX_NETWORK_DISABLED = True

DOCKER_SANDBOX_READ_ONLY_ROOT = True